<a href="https://colab.research.google.com/github/BuberDev/Machine_Learning/blob/main/Numpy03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. W zmiennej X zapisz tablicę dwuwymiarową z kolejnymi liczbami od 1 do 25. (Skorzystaj z arange() i reshape())

In [7]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

________________________________________________________________

2. W zmiennej Ones zapisz tablicę o takim samym kształcie jak X, ale całą wypełnioną tylko jedynkami. (Skorzystaj z ones())

In [11]:
Ones = np.ones(x.shape)
Ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

______________________________________________________________________________

3. Kiedy mnożąc przez siebie zwykłe liczby, chcesz żeby liczba pomnożona przez jakąś wartość dawała w wyniku tą samą liczbę, to tą jakąś wartością powinno być 1 (tzw. element neutralny). Czy tablica Ones jest taką "macierzową jedynką"? Sprawdź to  mnożąc przez siebie X i Ones. Czy wynik jest równy X? (Skorzytaj z dot() )

In [12]:
np.dot(x,Ones)

array([[ 10.,  10.,  10.,  10.,  10.],
       [ 35.,  35.,  35.,  35.,  35.],
       [ 60.,  60.,  60.,  60.,  60.],
       [ 85.,  85.,  85.,  85.,  85.],
       [110., 110., 110., 110., 110.]])

___________________________


4. W algebrze macierzy elementem neutralnym jest macierz zer, wypełniona jedynkami na przekątnej.

- Do zmiennej diag zapisz macierz o takich wymiarach jak X i wypełnioną samymi zerami (skorzystaj z zeros())

- Wypełnij diag jedynkami na przekątnej. (Skorzystaj z fill_diagonal()

- Pomnóż przez siebie X i diag i sprawdź czy wynik to X. (Skorzystaj z dot())

In [15]:
diag = np.zeros(x.shape)
diag

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.fill_diagonal(diag,1)
diag

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.dot(x,diag)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

_________________________

5. Wyświetl tablicę o wymiarach takich jak X, gdzie (we wszystkich punktach korzystaj z where):

- występują tylko jedynki i zera. Jedynki mają się pojawić tam, gdzie w X występuje wartość większa od 10, a zero w pozostałych przypadkach

- występują tylko jedynki i zera. Jedynki mają się pojawiać tam, gdzie w X występuje wartość parzysta, a zero w pozostałych przypadkach

- występują tylko liczby parzyste. Jeśli w X wartość była parzysta, to należy ją przepisać. Jeśli była nieparzysta , to dodać 1-

In [18]:
np.where(x > 10, 1,0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.where(x%2==0,1,0)

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [20]:
np.where(x % 2 == 0, x, 0)

array([[ 0,  0,  2,  0,  4],
       [ 0,  6,  0,  8,  0],
       [10,  0, 12,  0, 14],
       [ 0, 16,  0, 18,  0],
       [20,  0, 22,  0, 24]])

______________________


6. Utwórz tablicę X_bis wyznaczoną w następujący sposób. Dla wartości w X większych od 10 zwrócona jest wartość 2 razy większa, a dla pozostałych 0. Policz ile jest elementów niezerowych w X_bis (skorzystaj z count_nonzero())



In [22]:
X_bis = np.where(x > 10, x *2,0)
X_bis

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [23]:
np.count_nonzero(X_bis)

14

________________


7. Oto dwie tablice:

  x = np.array([[10,20,30], [40,50,60]])

  y = np.array([[100], [200]])


Dodaj (a właściwie doklej) do tablicy x tablicę y jako nową kolumnę. (Skorzystaj z append() z parametrem axis=1)

In [24]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])

In [25]:
np.append(x, y, axis=1)

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

_________


8. Oto dwie tablice:

    x = np.array([[10,20,30], [40,50,60]])
    
    y = np.array([[100, 200, 300]])


Dodaj (a właściwie doklej) do tablicy x tablicę y, jako nowy wiersz

In [26]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100, 200, 300]])

In [27]:
np.append(x, y, axis=0)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [100, 200, 300]])

_______

9. Do tablicy x z poprzedniego punktu, doklej tablicę x jako nowe wiersze (wiersze będą zduplikowane)

In [28]:
x = np.array([[10,20,30], [40,50,60]])

In [29]:
np.append(x,x, axis=1)

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])