<a href="https://colab.research.google.com/github/BuberDev/Machine_Learning/blob/main/Numpy_Basic_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Załaduj moduł numpy

In [ ]:
import numpy as np
import pandas as pd

2. Utwórz w zmiennej a jednowymiarową tablicę z elementami od 0 do 19. Hint: Służy do tego metoda np.arange(...)

In [ ]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

3. Wyświetl kształt tej tablicy. Hint: służy do tego właściwość shape

In [ ]:
a.shape

(20,)

4. Wyświetl zerowy element tablicy. Wyświetl czwarty element tablicy. Hint: Korzystaj z [] i numeruj od 0

In [ ]:
a[0]

0

In [ ]:
a[3]

3

5. Zmień kształt tablicy na 2x10. Wynik przekształcenia zapisz w a. Potem ponownie sprawdź kształt i wyświetl zawartość tablicy. Hint: Skorzystaj z metody reshape(...)

In [ ]:
a.reshape(2,10)
a.shape
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

6.  Wyświetl element zerowy z przekształconej w poprzednim kroku tablicy. Czy jest to ten sam element co poprzednio?

In [ ]:
a[0]

0

7. (Uwaga - tu będzie błąd, ale na błędach człowiek się uczy, więc to dobrze). Wyświetl czwarty element z tablicy a

In [ ]:
a[3]

3

8. A teraz zróbmy to poprawnie. Z tablicy a wyświetl czwarty element znajdujący się w zerowym wierszu. Hint: Musisz dwa razy skorzystać z [][]

In [ ]:
a[0]
a[3]
a[0][3]

IndexError: ignored

9. Zmień kształt tablicy a na 2x5x2

In [26]:
a.reshape(2,5,2)
a.shape


(20,)

In [27]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

10. Wyświetl z tablicy a:

zerowy wiersz

czwartą kolumnę z zerowego wiersza

drugi element z czwartego wiersza w zerowym wierszu

In [28]:
a[0]

0

12. Tworząc tablicę, możesz od razu definiować jej kształt. Utwórz tablicę b korzystając z parametrów przekazywanych do metody array lub wywołując odpowiednie metody dla już istniejącej tablicy, tak aby zawierała ona elementy parzyste od 0 do 40 o kształcie 4x5


In [30]:
b=np.arange(0,40,2).reshape(4,5)
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

Polecenie

a_python_list =  [2**x for x in range(10)]

tworzy standardową pythonową listę dziesięciu kolejnych potęg dwójki. W oparciu o tą listę utwórz obiekt array c



In [31]:
a_python_list =  [2**x for x in range(10)]

In [32]:
c = np.array(a_python_list)
c

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

14. To może się wydawać trochę dziwne, ale czasami w uczeniu maszynowym potrzebne są bardzo specyficzne obiekty array. W tym zadaniu utworzysz takie "dziwaczne" tablice

Utwórz tablicę zero_array składającą się z 10 zer. Hint: Skorzystaj z metody zeros

Utwórz tablicę one_array składającą się z 10 jedynek. Hint: Skorzystaj z metody ones

Utwórz tablicę empty_array składającą się ze 100  byle-jakich-liczb. Hint skorzystaj z metody empty
Ta metoda tworzy tablicę, która zawiera to, co akurat było w pamięci. Wielokrotne uruchamianie w/w polecenia może dawać różne wyniki, ale to nie jest jakiś świetny sposób na generowanie liczb losowych

Utwórz tablicę lucky_array o wymiarach 5x5 składającą się z samych trzynastek. Hint: Skorzystaj z metody full

Utwórz tablicę diagonal_array o wymiarach 5x5, która na przekątnej ma jedynki, a pozostałe wartości to zera. Hint: Skorzystaj z metody eye

Utwórz tablicę random_array składającą się z 10 losowych liczb. Hint: Skorzystaj z metody np.random.random

Utwórz tablicę linspace_array zawierającą 5 elementów, która jako zerową wartość ma 100, jako ostatnią ma wartość 200, i wszystkie elementy różnią się od siebie o tyle samo. Hint: Skorzystaj z metody linspace



In [34]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
one_array = np.ones(10)
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
empty_array = np.empty(100)
empty_array

array([2.87854187e-316, 6.90401257e-310, 6.90401257e-310, 6.90403256e-310,
       6.90401257e-310, 6.90401257e-310, 6.90403256e-310, 6.90401256e-310,
       6.90401258e-310, 6.90401257e-310, 6.90403256e-310, 6.90401258e-310,
       6.90401257e-310, 6.90403256e-310, 6.90401258e-310, 6.90401258e-310,
       6.90401257e-310, 6.90403256e-310, 6.90401257e-310, 6.90403256e-310,
       6.90401257e-310, 6.90401258e-310, 6.90401258e-310, 6.90401258e-310,
       6.90401258e-310, 6.90403256e-310, 6.90401257e-310, 6.90401258e-310,
       6.90401258e-310, 6.90403256e-310, 6.90401257e-310, 6.90401258e-310,
       6.90401256e-310, 6.90401258e-310, 6.90401258e-310, 6.90401258e-310,
       6.90401257e-310, 6.90403256e-310, 6.90401257e-310, 6.90403256e-310,
       6.90401258e-310, 6.90403256e-310, 6.90401258e-310, 6.90401258e-310,
       6.90401256e-310, 6.90403256e-310, 6.90401258e-310, 6.90401258e-310,
       6.90401258e-310, 6.90401257e-310, 6.90403256e-310, 6.90401258e-310,
       6.90401256e-310, 6

In [37]:
funny_array = np.full((5,5),13)
funny_array

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [40]:
diagonal_array = np.eye(5)
diagonal_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
random_array = np.random.random(10)
random_array

array([0.90474004, 0.27729078, 0.57787892, 0.78673291, 0.86221365,
       0.7702521 , 0.94646926, 0.28398818, 0.01328601, 0.35312401])

In [43]:
linspace_array = np.linspace(100,200, num=5)
linspace_array

array([100., 125., 150., 175., 200.])