<a href="https://colab.research.google.com/github/BuberDev/Machine_Learning/blob/main/Numpy_Basic_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Zacznijmy od zaimportowania numpy korzystając ze standardowego dla tego modułu aliasu

In [2]:
import numpy as np

2. Utwórz tablicę arr zawierającą nieparzyste liczby od 5 do 29. Hint: skorzystaj z funkcji arange

In [3]:
arr = np.arange(5,29,3)
arr

array([ 5,  8, 11, 14, 17, 20, 23, 26])

3. Utwórz tablicę boolArr zawierającą wartości True/False. True, gdy na odpowiedniej pozycji w arr jest liczba < 10, a False w przeciwnym razie. Hint: zacznij o wykonania operacji porównania na tablicy arr, a potem zapisz wynik w zmiennej



In [4]:
boolArr = arr < 10
boolArr

array([ True,  True, False, False, False, False, False, False])

4. Wyświetl tylko te pozycje z tablicy arr, gdzie:

na odpowiedniej pozycji w boolArr znajduje się wartość True. Hint: odwołując się do zawartości tablicy arr poprzez [] możesz przekazywać tablicę wartości logicznych

wartość pozycji jest < 20. Hint: warunek logiczny może być zapisywany bezpośrednio w []

wartość pozycji jest podzielna przez 3. Hint: Warunek logiczny powinien sprawdzać czy reszta z dzielenia pozycji tablicy przez 3 jest równa 0

wartość pozycji jest większa niż 10 i mniejsza niż 20. Hint: Warunek logiczny w [] może być bardziej skomplikowany, np. można skorzystać z operatora &



In [5]:
newArr = arr[boolArr]
newArr

array([5, 8])

In [6]:
newArr = arr[arr < 20]
newArr

array([ 5,  8, 11, 14, 17])

In [7]:
newArr = arr[arr%3==0]
newArr


array([], dtype=int64)

In [8]:
newArr = [(arr>10) & (arr<20)]
newArr

[array([False, False,  True,  True,  True, False, False, False])]

5. Zmień kształt arr na 4x6, a następnie wyświetl (pamiętaj o tym, że w pythonie numerujemy od zera, więc tutaj, zdecydowałem się pisać po pythonowemu - też liczę od zera):

pierwszy wiersz. Hint: korzystaj z []

z pierwszego wiersza drugą pozycję. Hint: korzystaj z podwójnego [numer_wiersza][numer_kolumny] lub z adresowania w postaci [numer wiersza, numer_kolumny]

z pierwszego wiersza pozycje od 2 do 3. Hint: Odwołując się do kolumn możesz skorzystać ze "slicing". Wartość określająca koniec zakresu do niego nie wchodzi (jak zwykle w Pythonie)

In [9]:
arr= np.arange(24).reshape(4,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
arr[1]

array([ 6,  7,  8,  9, 10, 11])

In [11]:
arr[1,2]

8

In [12]:
arr[1,2:4]

array([8, 9])

6. Zmień kształt arr na 4x6, a następnie wyświetl:
z pierwszego wiersza pozycje od 2 do 4. Hint: pamiętaj że ostatnia liczba z zakresu nie jest brana pod uwagę - przedział jest z prawej strony otwarty

z pierwszego wiersza wszystkie pozycje, ale budując to wyrażenie skorzystaj z notacji [numer_wiersza, zakres_kolumn]. Kiedy tworzysz zakres dla wszystkich kolumn - po prostu napisz :

z drugiej kolumny wszystkie wiersze. Hint: wyrażenie będzie podobne, co w poprzednim punkcie, tylko zmień kolejność w []

z wierszy od 0 do 2 wyświetl tylko 2 kolumnę. Hint: pamiętaj że ostatnia liczba z zakresu nie jest brana pod uwagę - przedział jest z prawej strony otwarty

wiersze do drugiego, druga kolumna. Hint: Istnieje odpowiednia notacja slice odpowiadająca za "do n-tego elementu"

wiersze do drugiego, kolumny od 2 do 3. Hint: Użyj operatora slice w odwołaniu do wiersza i do kolumny

wszystkie wiersze, ostatnia kolumna. Hint: Za odwołanie do ostatniej kolumny odpowiada zapis -1

wszystkie wiersze, wszystkie kolumny oprócz ostatniej. Hint: Zbuduj slice z : i liczbą -1

In [13]:
arr = np.arange(24).reshape(4,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
arr[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [15]:
arr[:,2]
arr[0:3,2]

array([ 2,  8, 14])

In [17]:
arr[:3,2]

array([ 2,  8, 14])

In [18]:
arr[:3,2:4]

array([[ 2,  3],
       [ 8,  9],
       [14, 15]])

In [21]:
#arr[:,5]
arr[:, -1]

array([ 5, 11, 17, 23])

In [22]:
arr[:,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

6. Do zmiennej arr zapisz tablicę 50-elementową, o wymiarach 10x5. Teraz trochę zbliżymy się do naszego celu, czyli jakiegoś "półautomatycznego" cięcia zbioru danych na dane uczące i testowe. Wykonaj polecenia:
___________________________________
##### how much data should be "test-data' - here 20%
split_level = 0.2

num_rows = arr.shape[0]

split_border = split_level * num_rows

__________________________________

Teraz zbuduj wyrażenie zwracające

wiersze od początku do split_border i wszystkie kolumny

wiersze od split_border do końca i wszystkie kolumny

Hint: wartość split_border, to liczba float. Zaokrąglij ją do liczby całkowitej podczas budowania slice (funkcja round)



In [23]:
arr = np.arange(50)
arr.reshape(10,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
arr.shape[0]

50

In [31]:
split_level = 0.2
num_rows = arr.shape[0]
split_border = split_level * num_rows



To już prawie dobry zbiór uczący i testowy, bo...  dane testowe byłyby zawsze brane z początku zbioru... a to trochę mało losowe. Dlatego "wymieszaj wiersze:

np.random.shuffle(arr)

i powtórz dzielenie tablicy arr na 20% i 80% jeszcze raz. Lepiej?

In [32]:
arr[:round(split_border), :]

IndexError: ignored

In [33]:
np.random.shuffle(arr)
arr

array([45, 35, 17, 11, 12, 30, 18,  5, 32, 49, 48, 23, 27, 26,  8, 14, 19,
        2, 25, 33, 42, 15, 40,  7, 10, 13, 44, 39, 34, 38, 20,  4, 28,  1,
        6,  3, 29, 16, 47,  0, 43, 41, 21, 37, 31, 24, 22, 46,  9, 36])

7. Finiszujemy. Napiszemy kod, który dzieli dane na uczące i testowe oraz rozdziela je na zbiór feature i zbiór target. Ostateczne oznaczenia mają być takie:

X_learn - 80% danych - wszystkie kolumny oprócz ostatniej
X_test - 20% danych - wszystkie kolumny oprócz ostatniej

y_learn - 80% danych - ostatnia kolumna

y_test - 20% danych - ostatnia kolumna

Oto dane:

data = np.arange(500).reshape(100,5)

Jeśli wiesz jak to zrobić, to jazda! A jak potrzebujesz dokładniejszych instrukcji, oto one:

przetasuj dane, żeby były ułożone losowo





In [36]:
data = np.arange(500).reshape(100,5)
data

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 1

In [38]:
np.random.shuffle(data)
data

array([[440, 441, 442, 443, 444],
       [ 60,  61,  62,  63,  64],
       [ 50,  51,  52,  53,  54],
       [240, 241, 242, 243, 244],
       [405, 406, 407, 408, 409],
       [480, 481, 482, 483, 484],
       [ 75,  76,  77,  78,  79],
       [375, 376, 377, 378, 379],
       [ 80,  81,  82,  83,  84],
       [195, 196, 197, 198, 199],
       [320, 321, 322, 323, 324],
       [290, 291, 292, 293, 294],
       [130, 131, 132, 133, 134],
       [295, 296, 297, 298, 299],
       [335, 336, 337, 338, 339],
       [385, 386, 387, 388, 389],
       [420, 421, 422, 423, 424],
       [ 65,  66,  67,  68,  69],
       [305, 306, 307, 308, 309],
       [225, 226, 227, 228, 229],
       [435, 436, 437, 438, 439],
       [100, 101, 102, 103, 104],
       [310, 311, 312, 313, 314],
       [ 40,  41,  42,  43,  44],
       [285, 286, 287, 288, 289],
       [ 95,  96,  97,  98,  99],
       [  0,   1,   2,   3,   4],
       [450, 451, 452, 453, 454],
       [180, 181, 182, 183, 184],
       [110, 1

Podobnie, jak w kodzie powyżej wyznacz nową wartość split_border, która określa ile wierszy będzie wziętych do danych testowych

Wyznacz X_test - wiersze od początku do split_border, wszystkie kolumny oprócz ostatniej

Wyznacz X_train - wiersze od split border do końca, wszystkie kolumny oprócz ostatniej

Wyznacz y_test - wiersze od początku do split_border, tylko ostatnia kolumna

Wyznacz y_train - wiersze od split_border do końca, tylko ostatnia kolumna

In [39]:
split_level = 0.2
num_rows = data.shape[0]
split_border = num_rows * split_level

In [40]:
X_train = data[round(split_border):,:-1]
X_test = data[:round(split_border),:-1]
y_test = data[:round(split_border),-1]
y_train = data[round(split_border):,-1]

In [41]:
data.shape

(100, 5)

Podobne czynności, co w punkcie 7, są wykonywane w train_test_split, a teraz ta funkcja nie jest już dla Ciebie tajemnicza. Fajnie, co?

from sklearn.model_selection import train_test_split
 
X_train, X_test, y_train, y_test = train_test_split(
        data[:, :-1], data[:, -1], test_size=0.2, shuffle = True)