<a href="https://colab.research.google.com/github/BuberDev/Machine_Learning/blob/main/Pytorch_Kurs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating tensors
Pytorch tensors are created using `torch.tensor()`


In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
# Hom many dimension
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9, 2]])
MATRIX

tensor([[7, 8],
        [9, 2]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
 # TENSOR
 TENSOR = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])
 TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random tensors

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(4,3)
print(random_tensor)
print(f"Shape of tensor:  {random_tensor.shape}")
print(f"Datatype of tensor:  {random_tensor.dtype}")
print(f"Device tensor is stored on: {random_tensor.device}")


tensor([[0.0736, 0.2649, 0.9975],
        [0.6777, 0.7315, 0.2938],
        [0.7094, 0.5075, 0.5812],
        [0.4529, 0.9238, 0.8342]])
Shape of tensor:  torch.Size([4, 3])
Datatype of tensor:  torch.float32
Device tensor is stored on: cpu


In [16]:
random_tensor.ndim

2

In [17]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 235, 3)) #hight, width, colour chanell(r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.size

(torch.Size([224, 235, 3]), <function Tensor.size>)

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(4,9)
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

torch.float32

In [20]:
# Create a tensor of all ones
ones = torch.ones(4,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

##Creating a range and tensors like

In [22]:
# Use torch.range
arange = torch.arange(3, 9, 1) # torch.arange(start=3, end=9, step=1)
arange

tensor([3, 4, 5, 6, 7, 8])

In [23]:
# Can also create a tensor of zeros similar to another tensor
some_zeros = torch.zeros_like(input=arange) # will have same shape
some_zeros

tensor([0, 0, 0, 0, 0, 0])

##Tensor datatypes

In [24]:
# Default dastatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 4.0, 8.0],# defaults to None, which is torch.float32 or whatever datatype is passed
                               dtype=None, # defaults to None, which uses the default tensor type
                               requires_grad=False)  # if True, operations performed on the tensor are recorded 
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
t_16_tensor = torch.tensor([4.0, 5.0, 8.0],
                               dtype=torch.float16)# torch.half would also work
t_16_tensor.dtype

torch.float16

##Basic operations

In [26]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [28]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [29]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [30]:
# Add and reassing
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [31]:
# We can also us torch functions 
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [32]:
# Orginal tensor is still unchanged
tensor

tensor([1, 2, 3])

In [33]:
# However, it's more common to use the operator symbols like * instead of torch.mul()
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [35]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [36]:
# Matrixx multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [38]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  value

CPU times: user 1.06 ms, sys: 10 µs, total: 1.07 ms
Wall time: 1.31 ms


In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 138 µs, sys: 0 ns, total: 138 µs
Wall time: 144 µs


tensor(14)

Reshape Tensors

In [59]:
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [60]:
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]), torch.Size([3, 4]))