<a href="https://colab.research.google.com/github/BuberDev/Machine_Learning/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating tensors
Pytorch tensors are created using `torch.tensor()`


In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
# Hom many dimension
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9, 2]])
MATRIX

tensor([[7, 8],
        [9, 2]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
 # TENSOR
 TENSOR = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])
 TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random tensors

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(4,3)
print(random_tensor)
print(f"Shape of tensor:  {random_tensor.shape}")
print(f"Datatype of tensor:  {random_tensor.dtype}")
print(f"Device tensor is stored on: {random_tensor.device}")


tensor([[0.6713, 0.4843, 0.2012],
        [0.6732, 0.7263, 0.0886],
        [0.3511, 0.1253, 0.0057],
        [0.2297, 0.6523, 0.6363]])
Shape of tensor:  torch.Size([4, 3])
Datatype of tensor:  torch.float32
Device tensor is stored on: cpu


In [12]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 235, 3)) #hight, width, colour chanell(r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.size

(torch.Size([224, 235, 3]), <function Tensor.size>)

In [13]:
# Create a tensor of all zeros
zeros = torch.zeros(4,9)
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
zeros.dtype

torch.float32

In [15]:
# Create a tensor of all ones
ones = torch.ones(4,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

##Creating a range and tensors like

In [17]:
# Use torch.range
arange = torch.arange(3, 9, 1) # torch.arange(start=3, end=9, step=1)
arange

tensor([3, 4, 5, 6, 7, 8])

In [18]:
# Can also create a tensor of zeros similar to another tensor
some_zeros = torch.zeros_like(input=arange) # will have same shape
some_zeros

tensor([0, 0, 0, 0, 0, 0])

##Tensor datatypes

In [4]:
# Default dastatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 4.0, 8.0],# defaults to None, which is torch.float32 or whatever datatype is passed
                               dtype=None, # defaults to None, which uses the default tensor type
                               requires_grad=False)  # if True, operations performed on the tensor are recorded 
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [5]:
t_16_tensor = torch.tensor([4.0, 5.0, 8.0],
                               dtype=torch.float16)# torch.half would also work
t_16_tensor.dtype

torch.float16

##Basic operations

In [6]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [7]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [8]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [9]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [10]:
# Add and reassing
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [12]:
# We can also us torch functions 
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [13]:
# Orginal tensor is still unchanged
tensor

tensor([1, 2, 3])

In [ ]:
# However, it's more common to use the operator symbols like * instead of torch.mul()
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

In [14]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [15]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [16]:
# Matrixx multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [17]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [18]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  value

CPU times: user 1.65 ms, sys: 72 µs, total: 1.73 ms
Wall time: 1.98 ms


In [19]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 87 µs, sys: 11 µs, total: 98 µs
Wall time: 102 µs


tensor(14)