<a href="https://colab.research.google.com/github/BuberDev/Machine_Learning/blob/main/Pytorch_Kurs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating tensors
Pytorch tensors are created using `torch.tensor()`


In [69]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [70]:
# Hom many dimension
scalar.ndim

0

In [71]:
# Get tensor back as Python int
scalar.item()

7

In [72]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [73]:
vector.ndim

1

In [74]:
vector.shape

torch.Size([2])

In [75]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9, 2]])
MATRIX

tensor([[7, 8],
        [9, 2]])

In [76]:
MATRIX.ndim

2

In [77]:
MATRIX.shape

torch.Size([2, 2])

In [78]:
 # TENSOR
 TENSOR = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])
 TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [79]:
TENSOR.ndim

3

In [80]:
TENSOR.shape

torch.Size([1, 3, 3])

In [81]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random tensors

In [82]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(4,3)
print(random_tensor)
print(f"Shape of tensor:  {random_tensor.shape}")
print(f"Datatype of tensor:  {random_tensor.dtype}")
print(f"Device tensor is stored on: {random_tensor.device}")


tensor([[0.7517, 0.5741, 0.5824],
        [0.1490, 0.8155, 0.1581],
        [0.4964, 0.5183, 0.9646],
        [0.8521, 0.8960, 0.1616]])
Shape of tensor:  torch.Size([4, 3])
Datatype of tensor:  torch.float32
Device tensor is stored on: cpu


In [83]:
random_tensor.ndim

2

In [84]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 235, 3)) #hight, width, colour chanell(r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.size

(torch.Size([224, 235, 3]), <function Tensor.size>)

In [85]:
# Create a tensor of all zeros
zeros = torch.zeros(4,9)
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
zeros.dtype

torch.float32

In [87]:
# Create a tensor of all ones
ones = torch.ones(4,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [88]:
ones.dtype

torch.float32

##Creating a range and tensors like

In [89]:
# Use torch.range
arange = torch.arange(3, 9, 1) # torch.arange(start=3, end=9, step=1)
arange

tensor([3, 4, 5, 6, 7, 8])

In [90]:
# Can also create a tensor of zeros similar to another tensor
some_zeros = torch.zeros_like(input=arange) # will have same shape
some_zeros

tensor([0, 0, 0, 0, 0, 0])

##Tensor datatypes

In [91]:
# Default dastatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 4.0, 8.0],# defaults to None, which is torch.float32 or whatever datatype is passed
                               dtype=None, # defaults to None, which uses the default tensor type
                               requires_grad=False)  # if True, operations performed on the tensor are recorded 
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [92]:
t_16_tensor = torch.tensor([4.0, 5.0, 8.0],
                               dtype=torch.float16)# torch.half would also work
t_16_tensor.dtype

torch.float16

##Basic operations

In [93]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [94]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [95]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [96]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [97]:
# Add and reassing
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [98]:
# We can also us torch functions 
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [99]:
# Orginal tensor is still unchanged
tensor

tensor([1, 2, 3])

In [100]:
# However, it's more common to use the operator symbols like * instead of torch.mul()
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [101]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [102]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [103]:
# Matrixx multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [104]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [105]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  value

CPU times: user 332 µs, sys: 45 µs, total: 377 µs
Wall time: 389 µs


In [106]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 134 µs, sys: 0 ns, total: 134 µs
Wall time: 139 µs


tensor(14)

Reshape Tensors

In [107]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [108]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

View


In [112]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [113]:
# Changing z changes x(because a view of a tensor shares the same memory aas the orginal). I want to change the all elements in the first column.
z[:,0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

Stack

In [114]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [115]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [116]:

# torchsqueeze() - removes all single dimensions from a target tensor
print(f"Previous Tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeeze = x_reshaped.squeeze()
x_squeeze
print(f"\nSqueezed tenor: {x_squeeze}")
print(f"Squeezed tenor shape: {x_squeeze.shape}")


Previous Tensor : tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

Squeezed tenor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Squeezed tenor shape: torch.Size([9])


In [121]:
# torch.unsqueeze() - adds a single dimension to target tensor at a specific dim (dimension) 
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
print(f"Add an extra dimension: {x_unsqueeze}")
print(f"Extra dim shape: {x_unsqueeze.shape}")

Add an extra dimension: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Extra dim shape: torch.Size([1, 9])


In [123]:
# torch.permute rearranges the dimensions of target tensor in a specific order
x_orginal = torch.rand(size=(224,224,3)) #[height, width, colour_channels]
#  the orginal tensor to rearrange the axis (or dim) order
x_permuted = x_orginal.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
x_permuted

print(f"Previous shape: {x_orginal.shape}")
print(f"Permuted shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


### Indexing

In [128]:
# Create tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [130]:
# Let's index on our new tensor
x[0]
 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [131]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [132]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [137]:
# Can also use ":" to select "all" of a target dimension
x[:, 1]

tensor([[4, 5, 6]])

In [138]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [139]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd  dimension
x[:, 1, 1]

tensor([5])

In [142]:
# Get index 0 of 0th  and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [145]:
# Index on x to return 9
x[0,2,2] 

tensor(9)

In [151]:
# Index on x to return 3, 6, 9
x[0,:,2]

tensor([3, 6, 9])

In [153]:
# Also
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & NumPy

In [155]:
# NumPy array to tensor
import torch 
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Normaly PyTorch has default datatype value 32, but when converting from NP -> PT, then pytorch get 64 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [156]:
# Change value of array, what will do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [157]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor



(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [158]:
# Change the tensor, what that happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural networt works

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again...`

To reduce the randomness in neural networ and PyTorch comes the concept of a ***random seed***. 
Essentially what the random seed does is "flavour" the randomness

In [162]:
import torch

# Create 2 random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.2207, 0.0566, 0.5111, 0.7346],
        [0.9121, 0.9918, 0.3452, 0.2510],
        [0.1563, 0.5781, 0.4184, 0.1161]])
tensor([[0.8120, 0.0997, 0.5745, 0.5261],
        [0.9841, 0.5725, 0.8674, 0.9705],
        [0.3348, 0.2267, 0.2926, 0.6796]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [169]:
# Let's make some random but reproducible tensors
import torch
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensor objects on the GPUs 

In [1]:
!nvidia-smi

Fri Feb 10 22:31:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P0    25W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [5]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
# Count number of devices 
torch.cuda.device_count()

1

## Putting tensors (and Models) on the GPU

In [9]:
# Create tensor(default on the CPU)
tensor = torch.tensor([1, 2, 3], device='cpu')

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [11]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')